name: Feature Request
description: Propose a new feature
body:
- type: markdown
  attributes:
    value: 'Thanks for taking the time to fill out this issue!

      '
- type: textarea
  id: description
  attributes:
    label: Description
    description: A Description of the issue
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version is this occurring in?
    options:
    - dev
    - 5.1
    - 5.0
    - 4.2
    - 4.1
    - 4.0
    - 3.2
    - 3.1
    - 3.0
    - 2.2
    - 2.1
    - 2.0
- type: input
  id: keywords
  attributes:
    label: Keywords
    description: Keywords to help categorize the issue
- type: checkboxes
  id: has-patch
  attributes:
    label: Has Patch
    options:
    - label: Has Patch
      required: false
- type: checkboxes
  id: ui-ux
  attributes:
    label: UI/UX
    options:
    - label: UI/UX
      required: false
- type: dropdown
  id: component
  attributes:
    label: Component
    description: Which component is affected?
    options:
    - contrib.admin
    - contrib.admindocs
    - contrib.auth
    - contrib.contenttypes
    - contrib.flatpages
    - contrib.humanize
    - contrib.messages
    - contrib.postgres
    - contrib.redirects
    - contrib.sessions
    - contrib.sitemaps
    - contrib.sites
    - contrib.staticfiles
    - contrib.syndication
    - Core (Cache system)
    - Core (Mail)
    - Core (Management commands)
    - Core (Other)
    - Core (Serialization)
    - Core (System checks)
    - Core (URLs)
    - CSRF
    - Database layer (models, ORM)
    - Documentation
    - Error reporting
    - File uploads/storage
    - Forms
    - Generic views
    - GIS
    - HTTP handling
    - Internationalization
    - Migrations
    - Packaging
    - Template system
    - Testing framework
    - Uncategorized (default selected)
    - Utilities
  validations:
    required: true
- type: dropdown
  id: severity
  attributes:
    label: Severity
    description: How severe is this issue?
    options:
    - Normal
    - Release Blocker
  validations:
    required: true
- type: checkboxes
  id: easy-pickings
  attributes:
    label: Easy Pickings
    options:
    - label: Easy Pickings
      required: false
